### ISSUE TITLE
Does Han-Western spacing apply to combination of “%” and Hanzi?

### ISSUE THREAD

**Issue by AmeroHan** [w3c/clreq#630] opened 2024-08-31 09:15 UTC
Take the sentence “约70%的受访者” as an example. On Microsoft Word, while there is spacing between “约” and “70”, there is no spacing between “%” and “的”, which results in an unbalanced look.

![A screenshot of Microsoft Word, showing the text layout of “约70%的受访者”](https://github.com/user-attachments/assets/a151ab42-a440-4b04-bb6b-3abcf737b294)

CSS Text Module Level 4 defined a [`text-autospace` property](https://www.w3.org/TR/css-text-4/#propdef-text-autospace). On newer Chrome, [enable experimental feature](https://developer.chrome.google.cn/blog/css-i18n-features#inter-script_spacing_text-autospace) and set `text-autospace: normal;` (currently equivalent to `text-autospace: ideograph-alpha ideograph-numeric;`), and no spacing will be inserted after “%”, too. After all, “%” doesn't belong to letters and numerals.

On iOS however, there is spacing inserted. I prefer this.

![A screenshot of input box on iOS, showing the text layout of “测试100%间距”](https://github.com/user-attachments/assets/ad8de801-5804-4016-b84b-74d4b38ba033)
![A screenshot of input box on iOS, showing the text layout of “测试%号”](https://github.com/user-attachments/assets/951fce0e-6bab-4b25-9bf7-caf8fa60e9e8)

**Comment by xfq** [comment] 2024-09-01 01:28
Duplicate of #559

**Closed as not planned by xfq** 2024-09-01 01:28 UTC
Labels: 問題/question
