### ISSUE TITLE
Language button not effective 

### ISSUE THREAD

**Issue by ryukeikun** [w3c/clreq#283] opened 2020-04-16 05:06 UTC
Even "Simplified Chinese" button clicked, the English table in § 2.3.5.2 still appears.

And, should the English paragraphs in the  header of document, including "Abstract", "Status of This Document" also be hidden?

**Comment by xfq** [comment] 2020-04-17 03:50
> Even "Simplified Chinese" button clicked, the English table in § 2.3.5.2 still appears.

Duplicate of https://github.com/w3c/clreq/issues/235

**Comment by xfq** [comment] 2020-04-17 03:50
> And, should the English paragraphs in the  header of document, including "Abstract", "Status of This Document" also be hidden?

@r12a Do you think we should do this?

**Comment by r12a** [comment] 2020-04-17 10:25
> And, should the English paragraphs in the header of document, including "Abstract", "Status of This Document" also be hidden?

This is complicated, because that text is supplied automatically from the respec template.  I did provide a translation for the template when it's a question of a Chinese-only document. But here we have a multilingual, switchable document; so that isn't relevant.

I figured that this is text that people don't often read, and we do provide a Chinese translation as well, and it legal-type stuff, so i didn't worry too much about it.

> Even "Simplified Chinese" button clicked, the English table in § 2.3.5.2 still appears.

That one we should try to fix.  It wasn't immediately obvious to me what causes that.

**Comment by xfq** [comment] 2020-04-17 11:39
> > Even "Simplified Chinese" button clicked, the English table in § 2.3.5.2 still appears.
> 
> That one we should try to fix.  It wasn't immediately obvious to me what causes that.

Because `table.charsize` has `display: inline-table`: https://github.com/w3c/clreq/blob/cb2c6a7fffb18cffde6d60dd672e705b8baf1641/local.css#L217-L218


Since the `hidden` attribute is [implemented in CSS](https://html.spec.whatwg.org/multipage/rendering.html#hiddenCSS), it is overridden by the `display: inline-table` in the CSS. See https://github.com/w3c/clreq/issues/235#issuecomment-568832236 for my proposed solution for this issue.

**Closed as completed** 2021-01-13 11:54 UTC
